### ISSUE TITLE
Add annotations for stability index

### ISSUE THREAD

**Issue by donaldpipowitch** [jayphelps/core-decorators.js#1]
I love your project. I thought of the same the first time I saw decorators. As you already support `@deprecate (alias: @deprecated)` I'd encourage you to support the whole set of stability indices major projects like Node.js and Rust use. Taken from [Node](https://nodejs.org/api/documentation.html):

````
Stability: 0 - Deprecated
This feature is known to be problematic, and changes are
planned.  Do not rely on it.  Use of the feature may cause warnings.  Backwards
compatibility should not be expected.

Stability: 1 - Experimental
This feature was introduced recently, and may change
or be removed in future versions.  Please try it out and provide feedback.
If it addresses a use-case that is important to you, tell the node core team.

Stability: 2 - Unstable
The API is in the process of settling, but has not yet had
sufficient real-world testing to be considered stable. Backwards-compatibility
will be maintained if reasonable.

Stability: 3 - Stable
The API has proven satisfactory, but cleanup in the underlying
code may cause minor changes.  Backwards-compatibility is guaranteed.

Stability: 4 - API Frozen
This API has been tested extensively in production and is
unlikely to ever have to change.

Stability: 5 - Locked
Unless serious bugs are found, this code will not ever
change.  Please do not suggest changes in this area; they will be refused.
````

It could look like this:

````
@deprecated
someFunction() {}

@experimental
someFunction() {}

@unstable
someFunction() {}

@stable
someFunction() {}

@frozen
someFunction() {}

@locked
someFunction() {}
````

I think Rust defaults to compile everything above and including `3 - Stable`. For JavaScript I'd default to `console.warn()` to everything below `3 - Stable` allowing the developer to opt-in to a different stability index by setting an environment variable for Node.js and a global variable for Browsers.

Personally I'd would also prefer to have just `@deprecated` and no alias to `@deprecate`. I prefer to be more strict here.

**Comment by donaldpipowitch** [comment]
@wycats As someone who knows the Rust world more in-depth - is this something we want to have in the JavaScript world, too? Would you use something like that in Ember?

**Comment by wycats** [comment]
@donaldpipowitch both Ember and Rust have moved to a release channel system, so there is only:

* unstable, which you can enable with a feature flag on nightly/canary only
* stable, which first lands in beta builds and then into the release builds
* deprecated, which means that a feature may be removed at the next major release (SemVer)

Decorators might not be at the right granularity to feature-flag features (which often branch in the middle of functions), but something like `@since("1.0")` and `@deprecated` both seem pretty useful.

**Comment by donaldpipowitch** [comment]
Thank you very much for the feedback. I guess this issue should be closed then? At least until someone has a good usage for this.
