### ISSUE TITLE
Consider a rewrite of @readonly & @deprecate examples

### ISSUE THREAD

**Issue by addyosmani** [jayphelps/core-decorators.js#10]
It was brought to my attention on Twitter that two of the examples from the current README include gender and animal humour that causes offence. I've rewritten them in my [article](https://medium.com/@addyosmani/exploring-es7-decorators-76ecb65fb841) and would ask that we take into account the feelings of folks who may feel hurt by them. We're all human, but in case using my examples is of help.

`@readonly` rewritten to use a Meal/Dinner theme:

<img width="775" alt="screen shot 2015-07-10 at 00 22 47" src="https://cloud.githubusercontent.com/assets/110953/8609353/106f771e-269c-11e5-96cd-04505b50ffb5.png">

`@decorate` rewritten to use a Person -> Captain Picard theme:

```js

import { deprecate } from 'core-decorators';

class Person {
  @deprecate
  facepalm() {}

  @deprecate('We stopped facepalming')
  facepalmHard() {}

  @deprecate('We stopped facepalming', { url: 'http://knowyourmeme.com/memes/facepalm' })
  facepalmHarder() {}
}

let captainPicard = new Person();

captainPicard.facepalm();
// DEPRECATION Person#facepalm: This function will be removed in future versions.

captainPicard.facepalmHard();
// DEPRECATION Person#facepalmHard: We stopped facepalming

captainPicard.facepalmHarder();
// DEPRECATION Person#facepalmHarder: We stopped facepalming
//
//     See http://knowyourmeme.com/memes/facepalm for more details.
//
```

^ Note: The facepalm here is more to represent my own embarrassment at not having caught this sooner. It's my fault for not having caught this in my article before publishing.

**Comment by jayphelps** [comment]
https://github.com/jayphelps/core-decorators.js/commit/6f7a06255054dd8b272f795af2ce411c3a5974b2
