### ISSUE TITLE
Memoize

### ISSUE THREAD

**Issue by steida** [jayphelps/core-decorators.js#11]
https://github.com/google/closure-library/blob/master/closure/goog/memoize/memoize.js

**Comment by jayphelps** [comment]
Closing due to `@memoize` [now being deprecated](https://github.com/jayphelps/core-decorators.js/commit/9201eaba7ee0664972e551e63888aa35dcccef77) and soon to be removed.

**Comment by pascalduez** [comment]
Hi,

any hint on why this was deprecated ? Just curious.

**Comment by jayphelps** [comment]
@pascalduez primarily two factors: it was never really complete to begin with--definitely slow, likely buggy, second is that you can now use third party functions as decorators via the new `@decorate` decorator [described here](https://github.com/jayphelps/core-decorators.js/blob/master/README.md#decorate). Libraries like lodash contain well supported memoization implementations that can now be used, as well as many others.

That said, this is certainly a community project so if there is a consensus on having memoization built-in, and someone champions the implementation, it could see a return.

**Comment by pascalduez** [comment]
Thanks for the explanations. Makes sense.
I found myself in need of such functionality a couple of times, that's why I asked.
At the end I used [memoize-decorator](https://www.npmjs.com/package/memoize-decorator).
