### ISSUE TITLE
Fatal error in IE

### ISSUE THREAD

**Issue by artptr** [jayphelps/core-decorators.js#112]
There is an error in IE at initialization stage in profile decorator. `console.profile` there isn't a "normal" function with Function prototype, so calling `console.profile.bind(console)` causes an error.

Fixed in #111.

**Comment by jayphelps** [comment]
Was fixed unknowingly in #110, released in 0.18.0

**Comment by Anber** [comment]
It looks like you forget to build es-version before publish 0.18.0 to npm…

**Comment by jangot** [comment]
Yes, I have 0.19.0v and I  see the error in IE.
Why is it happen?

**Comment by jayphelps** [comment]
@jangot can you provide more details? When I search in 0.19.0 I cannot find any cases where we call console.profile.bind. Can you share where in our code it is? What version of IE?

Triple check you really do have 0.19.0 installed in your node_modules--you might have it in your package.json but an older version is in node_modules
