### ISSUE TITLE
missing changelog

### ISSUE THREAD

**Issue by dfleury** [jayphelps/core-decorators.js#114]
Hi there! I just wanna know if there is a place where I can see what's changing from a version to another.
Currently, there is no CHANGELOG.md, git tags are desynchronized from npm releases and by last, the [releases page](https://github.com/jayphelps/core-decorators.js/releases) is outdated either.
I'm a maintainer of a critical web project and I need extra caution when updating dependencies, which periodically I do. So what I need is a way to measure how risky an update is and what benefits is being provided in exchange.

**Comment by jayphelps** [comment]
The only way right now is to view the commit history. I use [conventional-changelog-standard](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md) in some of my other projects to generate a changelog, but core-decorators hasn't changed a whole lot and I haven't gotten around to setting it up.

**Comment by dfleury** [comment]
It has to be enough for now
