### ISSUE TITLE
Why is debounce & throttle deprecated?

### ISSUE THREAD

**Issue by isuvorov** [jayphelps/core-decorators.js#115]
Surprised and upset

@debounce 🚫 DEPRECATED
@throttle 🚫 DEPRECATED

**Comment by jayphelps** [comment]
See here: https://github.com/jayphelps/core-decorators.js/blob/master/README.md#need-lodash-utilities-as-decorators

They duplicate the effort of lodash-decorators and aren't as robust and tested as lodash is. Sorry that you're upset, I think this is very much for the best.
