### ISSUE TITLE
npm run build - fails from Windows command prompt

### ISSUE THREAD

**Issue by BurtHarris** [jayphelps/core-decorators.js#117]
Looks like the build script update for `es` output causes a failure for the windows platform.   It look to be driven by this line in `package.json`:

```
    "build": "babel --out-dir lib src && BABEL_ENV=es babel --out-dir es src",
```

I gather that starting the second command with `BABEL_ENV=es` is a bash convention for setting a temporary environment variable.  It doesn't work under `Command.exe`.   It seems like a cool feature for a shell, just not found everywhere.

**Comment by jayphelps** [comment]
https://www.npmjs.com/package/cross-env would solve this. I don't have a Windows machine to test, but if you get it working please do PR!

**Comment by BurtHarris** [comment]
**cross-env** sounds cool, thanks I'll have a look.   

P.S.  https://www.appveyor.com is free windows-based CI service (for public projects) could be useful.   I could probably submit a PR to enable it if you are interested..

**Comment by jayphelps** [comment]
@BurtHarris always interested in PRs like that! 👍

**Comment by BurtHarris** [comment]
Give me a few minutes, I'll add appveyor to my branch.

**Comment by BurtHarris** [comment]
Done!   Please have a look.
