### ISSUE TITLE
Puzzling code in unit tests

### ISSUE THREAD

**Issue by BurtHarris** [jayphelps/core-decorators.js#119]
I'm trying to run unit tests w/ TypeScript as the transpiler.   Got some errors where I don't understand the code, like this from test/unit/extendDescriptor.js

```javascript
  it('extends property initializers', function () {
    Object.getOwnPropertyDescriptor(Derived.prototype, 'fourth');
      .enumerable.should.equal(false);   // *** ERROR HERE ***

    derived.fourth.should.equal('fourth');
  });
```
What's the `.enumerable` mean when there's a `;` before it?  

```cmd
C:\code\core-decorators.js\test>tsc
unit/extendDescriptor.js(82,7): error TS1128: Declaration or statement expected.
unit/extendDescriptor.js(89,7): error TS1128: Declaration or statement expected.
unit/mixin.spec.js(22,10): error TS1109: Expression expected.
unit/mixin.spec.js(37,17): error TS1109: Expression expected.
```

**Comment by BurtHarris** [comment]
I figured that maybe the semicolon was a typo, but removing it doesn't fix the problem.   

I guess enumerable is sort of an extension function on boolean, but TypeScript doesn't understand it.

**Comment by BurtHarris** [comment]
Found a workaround...

**Comment by jayphelps** [comment]
@BurtHarris not sure why you're seeing a semicolon there? It's not in the source https://github.com/jayphelps/core-decorators.js/blob/master/test/unit/enumerable.spec.js#L10
