### ISSUE TITLE
Deprecate decorator

### ISSUE THREAD

**Issue by dfsq** [jayphelps/core-decorators.js#12]
With recent changes (commit https://github.com/jayphelps/core-decorators.js/commit/af4023c2a5f3875413de9e2c265b6c3491df29bc) deprecate decorator fails to pass message properly, it only uses the first character since `...arg` converts string into array of characters.

**Comment by jayphelps** [comment]
Thanks @dfsq for reporting! Fixed and published as `v0.1.5`
