### ISSUE TITLE
Why does test/unit/extendDescriptor.js not have .spec in its name?

### ISSUE THREAD

**Issue by BurtHarris** [jayphelps/core-decorators.js#132]
It seems to be the only file without a `.spec` in [this directory](https://github.com/jayphelps/core-decorators.js/tree/master/test/unit).

Is the exception from the naming convention supposed to indicate something?

**Comment by jayphelps** [comment]
Looks like a mistake, which may or may not be actually causing it to be excluded from testing.

**Comment by BurtHarris** [comment]
The reason I'm asking is if I include it, there was a failure.   Just wanted to check with you before I debug it.

**Comment by BurtHarris** [comment]
Reopened as reminder to change and debug this.
