### ISSUE TITLE
More spec about assertArguments

### ISSUE THREAD

**Issue by RobinQu** [jayphelps/core-decorators.js#19]
I'd like to implment `assertArguments` decorator, but found little info about this.

Does it mean no spec is defined for this decorator, so I can write it the way I like?

**Comment by jayphelps** [comment]
Correct, there isn't any spec. I was thinking something along the lines of:

```js
class Bank {
  @assertArguments(
    accountNumber => isValidNumber(accountNumber),
    arg2 => arg2
  )
  withdrawal(accountNumber, amount) {
    // ...
  }
}

```

**Comment by jayphelps** [comment]
closing for now, feel free to jump in.
