### ISSUE TITLE
autobind not properly working for child and parent classes

### ISSUE THREAD

**Issue by hasdavidc** [jayphelps/core-decorators.js#20]
```
import { autobind } from 'lib/decorators';

class AwesomeClass {

  @autobind
  awesomeMethod() {
    console.log('parent called, AWESOME METHOD');
  }

}

class AwesomeChildClass extends AwesomeClass {

  @autobind
  awesomeMethod() {
    console.log('child called, AWESOME CHILD METHOD');
    super.awesomeMethod();
  }

}

let instance = new AwesomeChildClass();

for (var i = 0; i < 5; ++i) {
  console.log('invoking');
  instance.awesomeMethod();
  console.log('---');
}
```

The first time, both child and parent messages are logged to the console; the next 4 times, only the parent message is logged. Is this the expected behavior?

**Comment by jayphelps** [comment]
Thanks for reporting this! This is definitely not intended, but it's actually surprisingly complex to solve. The only way I know of without creating memory leaks or obtrusively setting extraneous properties on the instance requires the use of `WeakMap`. I went ahead and implemented it here https://github.com/jayphelps/core-decorators.js/pull/21, take a peak. I'm gonna let it sit for bout a day then come back to this with fresh eyes and try to confirm I'm not missing something.

**Comment by jayphelps** [comment]
@hasdavidc fix released as `core-decorators@0.4.2`. Be sure to include a [WeakMap polyfill](https://www.npmjs.com/package/es6-weak-map) if you support older browsers. Thanks again!

**Comment by hasRandy** [comment]
Wow @jayphelps, fantastic turnaround on that. Thanks so much!

**Comment by jayphelps** [comment]
@hasRandy You're welcome!

**Comment by hasdavidc** [comment]
amazing turnaround, quite impressive! just upgraded the npm version (and added a polyfill) and everything worked perfectly - thanks again for your work @jayphelps
