### ISSUE TITLE
@enumerable?

### ISSUE THREAD

**Issue by bathos** [jayphelps/core-decorators.js#27]
The default property descriptor value for methods is `enumerable: false`. It seems there’s no `@enumerable` decorator currently.

Relatedly, `@nonenumerable` should probably not be listed as a method decorator, since in this role it wouldn't do anything; it is only meaningful as a decorator for ES7 class properties, which do default to `enumerable: true` currently.

**Comment by jayphelps** [comment]
Right on. Thanks @bathos!!
