### ISSUE TITLE
[suggestion] @chainable decorator for functions

### ISSUE THREAD

**Issue by darkyen** [jayphelps/core-decorators.js#29]
Chaning is a common pattern I was wondering what stops from a method for creating chainables ?

Example
```javascript

class Foo{
    @chainable
    bar(){
    }
 
    baz(){
    }
}

const f = new Foo();
f.bar().bar().bar().baz();
```

**Comment by jayphelps** [comment]
IMO just using `return this;` is more idiomatic. Thoughts on why a decorator would be an improvement? Wouldn't it be confusing because someone could write `return somethingElse;` but all return values would effectively be silently thrown away?

```js
class Foo {
  bar() {
    return this; 
  }

  baz() {
  }
}

const f = new Foo();
f.bar().bar().bar().baz();
```

**Comment by gig177** [comment]
I agree with jayphelps. What does improve this decorator?

**Comment by darkyen** [comment]
@jayphelps maybe, I just liked using a decorator a little more.

**Comment by jayphelps** [comment]
@darkyen Very much appreciate the input. As of now I think this is better left to `return this`. Thanks again!
