### ISSUE TITLE
Maybe add simple profiler?

### ISSUE THREAD

**Issue by LestaD** [jayphelps/core-decorators.js#37]
### Usage

```js
class UserPage extends Controller {
  @Timer()
  actionHome() {
    this.render('user/home', { user: this.global.user });
  }
}
```

Console:

```
Run UserPage.actionHome()
End UserPage.actionHome(): 3.765ms
```

[LestaD/Decorators#Timer](https://github.com/LestaD/ES6-Decorators#timer)

**Comment by pete-otaqui** [comment]
I think there are a couple of issues with the way you create the timer:

* Nested calls may interfere with each other since they share a label
* console.time is not available in all browsers & js environments.

I'm also working on a version of this, will reply on this ticket shortly.

**Comment by pete-otaqui** [comment]
Here's the PR:

https://github.com/jayphelps/core-decorators.js/pull/38

**Comment by jayphelps** [comment]
#38 has been merged.
