### ISSUE TITLE
IE8 Not supported

### ISSUE THREAD

**Issue by gdzgshum** [jayphelps/core-decorators.js#39]
ERROR: ,Object.defineProperty(e,a.key,a)

i have import : 
respond.min.js,
html5shiv.min.js,
jquery.min.js,

component/console-polyfill/0.2.2/index.js,
component/es5-shim/4.1.14/es5-shim.min.js,
component/es5-shim/4.1.14/es5-sham.min.js,
component/media-match/2.0.2/media.match.min.js

**Comment by jayphelps** [comment]
This is tough. IE8 doesn't support `Object.defineProperty` which is used appropriately by core-decorators so if I don't use it or fall back to regular assignment, the behavior will differ slightly and could actually cause really bugs in your code that may rely on it. You could certainly provide your own broken `Object.defineProperty` shim that causes it to work just as well as what I'd have to do, realizing the caveats of course.

I'll definitely think about this, but ultimately I already realized IE8 wasn't supported and assumed the web had moved to a point where this was mostly a non-issue for anyone using such advanced features likes decorators.

I do realize you gotta support what you gotta support, I've been there, so I feel for you.

**Comment by yordis** [comment]
:-1:  for any IE8 support. Please don't expend any time on that :cry: it's 2016

**Comment by pete-otaqui** [comment]
Since MS dropped support for all IE's less than 11 *today* I don't think it's worth a library like this spending effort on support for version 8.

**Comment by jayphelps** [comment]
I thought pretty hard on this and I'm gonna have to confirm this will not support IE8 out of box. I really need `defineProperty` and any patch I include just for IE8 will just create footguns for devs where the patch doesn't work as expected since it's impossible to completely shim `defineProperty`.

Sorry!
