### ISSUE TITLE
Create decorator to overcome limitations of ECMAScript concerning overriding setters/getters with inheritance

### ISSUE THREAD

**Issue by silkentrance** [jayphelps/core-decorators.js#50]
Original discussion found in #44

### Possible names:

`@getset`
`@inheritprop`
`@merge`
`@inherit`
`@inheritDescriptor`
`@mergeDescriptor`
`@mergeExistingDescriptor`
`@mergeProperty` ([@RReverser](https://twitter.com/RReverser/status/701923789894979591))
`@defineProperty` ([@RReverser](https://twitter.com/RReverser/status/701925660105768960))
- - -

See https://phabricator.babeljs.io/T2449 and the limitation of the Javascript spec, which will not allow one to just override a getter or a setter of a given property of the base class but instead will discard any such getters and setters when missing.

In turn you will have to redeclare the getters and setters all over again, e.g.

```
class Base {
    get name() ...
    set name(v) ...
}

class Derived
{
     set name(v)...
}
```

Now, instantiating Derived will allow you to set the name property, but you cannot get the value back as there is no getter.

How about allowing one to 

```
class Derived
{
   @override 
    set name(v)...
}
```

were ``@override`` would then fill in the missing getter, or setter, accordingly?

**Comment by silkentrance** [comment]
@jayphelps as for the name of the new decorator, how about something more easy to remember and type, e.g. ``@getset``?

**Comment by silkentrance** [comment]
Still a few things to flesh out though, what about integration with the existing other decorators, such as ``@readonly``? Or does this not apply to getters and setters?

**Comment by jayphelps** [comment]
@silkentrance correct, `@readonly` doesn't work with getters and setters since it just sets `descriptor. writable = true` which getter/setter descriptors don't support.

Otherwise, any decorator that worked before should indeed still work with this hypothetical descriptor AFAIK. They can be chained, this descriptor would just merge the existing descriptor. Like some of the decorators, the order of them may matter though.

One thing I can think of is `@nonconfigurable` probably would be blown away.

```js
class Base {
  get foo() {}
}

class Derived extends Base {
  @nonconfigurable
  @hypotheticalNewDecoratorThatMerges
  set foo() {}
}

Object.getOwnPropertyDescriptor(Derived.prototype, 'foo').configurable;
// true
```
Notice that `configurable === true` even though we we had used `@nonconfigurable` because the inherited descriptor had  `configurable === true`.

You'd need to use:

```js
class Derived extends Base {
  @hypotheticalNewDecoratorThatMerges
  @nonconfigurable
  set foo() {}
}
```

**Comment by jayphelps** [comment]
@silkentrance IMO `@getset` is too ambiguous.

**Comment by silkentrance** [comment]
@jayphelps Aren't these decorators chained? Of course, babel 5.x gets it the wrong way and only babel 6.x applies them according to the specification. So the first example where the ``@nonconfigurable`` decorator comes first is the correct approach according to babel 6.x whereas the second would accommodate the behavior of babel 5.x.

**Comment by silkentrance** [comment]
https://gist.github.com/silkentrance/8133476645f9ce7bcf5b for a first stab at the impl

**Comment by jayphelps** [comment]
@silkentrance babel 6 does not officially support decorators yet https://phabricator.babeljs.io/T2645 perhaps you referring to the unofficial [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) ? In that case, yep, you're correct. You're also correct in regards to TypeScript's behavior. Both of which are correct as per spec.

Anyways, you're correct that I was backwards in every case except the non-compliant babel 5.

**Comment by jayphelps** [comment]
What was wrong with my original example?

```js
function hypotheticalDecoratorThatMerges(target, key, descriptor) {
  if ('get' in descriptor || 'set' in descriptor) {
    const superKlass = Object.getPrototypeOf(target);
    const superDescriptor = Object.getOwnPropertyDescriptor(superKlass, key);
    // Merge the new descriptor in with the old one, which will
    // keep any existing get or set that we aren't overriding
    descriptor = { ...superDescriptor, ...descriptor };
  }

  return descriptor;
}

class Base {
  get foo() {
    return `hello ${this.value}`;
  }
}

class Derived extends Base {
  @hypotheticalDecoratorThatMerges
  set foo(value) {
    this.value = value;
  }
}

const derived = new Derived();
derived.foo = 'bar';
console.log(derived.foo);
```

[REPL Example](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20hypotheticalDecoratorThatMerges(target%2C%20key%2C%20descriptor)%20%7B%0A%20%20if%20('get'%20in%20descriptor%20%7C%7C%20'set'%20in%20descriptor)%20%7B%0A%20%20%20%20const%20superKlass%20%3D%20Object.getPrototypeOf(target)%3B%0A%20%20%20%20const%20superDescriptor%20%3D%20Object.getOwnPropertyDescriptor(superKlass%2C%20key)%3B%0A%20%20%20%20%2F%2F%20Merge%20the%20new%20descriptor%20in%20with%20the%20old%20one%2C%20which%20will%0A%20%20%20%20%2F%2F%20keep%20any%20existing%20get%20or%20set%20that%20we%20aren't%20overriding%0A%20%20%20%20descriptor%20%3D%20%7B%20...superDescriptor%2C%20...descriptor%20%7D%3B%0A%20%20%7D%0A%0A%20%20return%20descriptor%3B%0A%7D%0A%0Aclass%20Base%20%7B%0A%20%20get%20foo()%20%7B%0A%20%20%20%20return%20%60hello%20%24%7Bthis.value%7D%60%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Derived%20extends%20Base%20%7B%0A%20%20%40hypotheticalDecoratorThatMerges%0A%20%20set%20foo(value)%20%7B%0A%20%20%20%20this.value%20%3D%20value%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20derived%20%3D%20new%20Derived()%3B%0Aderived.foo%20%3D%20'bar'%3B%0Aconsole.log(derived.foo)%3B&stage=0)

**Comment by silkentrance** [comment]
@jayphelps Nothing is wrong with that example, I actually based the gist upon it. However, target can be either the class or the prototype (static vs. instance properties) so I felt that the decorator must differentiate between the two use cases.

**Comment by jayphelps** [comment]
hmmm if that's the case, this lib makes that mistake in all decorators that use `target`. But in my previous testing and now, it behavior seems correct? Can you verify?

[Example in REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20hypotheticalDecoratorThatMerges(target%2C%20key%2C%20descriptor)%20%7B%0A%20%20if%20('get'%20in%20descriptor%20%7C%7C%20'set'%20in%20descriptor)%20%7B%0A%20%20%20%20const%20superKlass%20%3D%20Object.getPrototypeOf(target)%3B%0A%20%20%20%20const%20superDescriptor%20%3D%20Object.getOwnPropertyDescriptor(superKlass%2C%20key)%3B%0A%20%20%20%20%2F%2F%20Merge%20the%20new%20descriptor%20in%20with%20the%20old%20one%2C%20which%20will%0A%20%20%20%20%2F%2F%20keep%20any%20existing%20get%20or%20set%20that%20we%20aren't%20overriding%0A%20%20%20%20descriptor%20%3D%20%7B%20...superDescriptor%2C%20...descriptor%20%7D%3B%0A%20%20%7D%0A%0A%20%20return%20descriptor%3B%0A%7D%0A%0Aclass%20Base%20%7B%0A%20%20static%20get%20foo()%20%7B%0A%20%20%20%20return%20%60hello%20%24%7Bthis.value%7D%60%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Derived%20extends%20Base%20%7B%0A%20%20%40hypotheticalDecoratorThatMerges%0A%20%20static%20set%20foo(value)%20%7B%0A%20%20%20%20this.value%20%3D%20value%3B%0A%20%20%7D%0A%7D%0A%0ADerived.foo%20%3D%20'bar'%3B%0Aconsole.log(Derived.foo)%3B&stage=0)

**Comment by silkentrance** [comment]
see above, just tested this with static and instance level props and it works just fine.

**Comment by silkentrance** [comment]
As for the name, how about ``@inheritprop`` or something along that line?

**Comment by jayphelps** [comment]
Yep, you're right it does blow away other descriptor options. I don't know why I thought it wouldn't. :dancers: 

This seems to be correct: [REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20hypotheticalDecoratorThatMerges(target%2C%20key%2C%20desc)%20%7B%0A%20%20if%20('get'%20in%20desc%20%7C%7C%20'set'%20in%20desc)%20%7B%0A%20%20%20%20const%20superKlass%20%3D%20Object.getPrototypeOf(target)%3B%0A%20%20%20%20const%20superDesc%20%3D%20Object.getOwnPropertyDescriptor(superKlass%2C%20key)%3B%0A%20%20%20%20const%20%7B%20get%2C%20set%20%7D%20%3D%20desc%3B%0A%20%20%20%20desc%20%3D%20%7B%0A%20%20%20%20%20%20...superDesc%2C%0A%20%20%20%20%20%20get%3A%20get%20%7C%7C%20superDesc.get%2C%0A%20%20%20%20%20%20set%3A%20set%20%7C%7C%20superDesc.set%0A%20%20%20%20%7D%3B%0A%20%20%7D%0A%0A%20%20return%20desc%3B%0A%7D%0A%0Afunction%20nonconfigurable(target%2C%20key%2C%20descriptor)%20%7B%0A%20%20descriptor.configurable%20%3D%20false%3B%0A%20%20return%20descriptor%3B%0A%7D%0A%0Aclass%20Base%20%7B%0A%20%20%40nonconfigurable%0A%20%20get%20foo()%20%7B%0A%20%20%20%20return%20%60hello%20%24%7Bthis.value%7D%60%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Derived%20extends%20Base%20%7B%0A%20%20%40hypotheticalDecoratorThatMerges%0A%20%20set%20foo(value)%20%7B%0A%20%20%20%20this.value%20%3D%20value%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20derived%20%3D%20new%20Derived()%3B%0Aderived.foo%20%3D%20'bar'%3B%0Aconsole.log(derived.foo)%3B%0A%2F%2F%20hello%20bar%0A%0Aconst%20desc%20%3D%20Object.getOwnPropertyDescriptor(Derived.prototype%2C%20'foo')%3B%0Aconsole.log(desc.configurable%20%3D%3D%3D%20false)%3B%0A%2F%2F%20true%0A%0AObject.defineProperty(Derived.prototype%2C%20'foo'%2C%20%7B%0A%20%20value%3A%20'not%20going%20to%20work'%0A%7D)%3B%0A%2F%2F%20Uncaught%20TypeError%3A%20Cannot%20redefine%20property%3A%20foo&stage=0)
```js
function hypotheticalDecoratorThatMerges(target, key, desc) {
  if ('get' in desc || 'set' in desc) {
    const superKlass = Object.getPrototypeOf(target);
    const superDesc = Object.getOwnPropertyDescriptor(superKlass, key);
    const { get, set } = desc;
    desc = {
      ...superDesc,
      get: get || superDesc.get,
      set: set || superDesc.set
    };
  }

  return desc;
}

function nonconfigurable(target, key, descriptor) {
  descriptor.configurable = false;
  return descriptor;
}

class Base {
  @nonconfigurable
  get foo() {
    return `hello ${this.value}`;
  }
}

class Derived extends Base {
  @hypotheticalDecoratorThatMerges
  set foo(value) {
    this.value = value;
  }
}

const derived = new Derived();
derived.foo = 'bar';
console.log(derived.foo);
// hello bar

const desc = Object.getOwnPropertyDescriptor(Derived.prototype, 'foo');
console.log(desc.configurable === false);
// true

Object.defineProperty(Derived.prototype, 'foo', {
  value: 'not going to work'
});
// Uncaught TypeError: Cannot redefine property: foo
```

**Comment by jayphelps** [comment]
`@inheritprop` still seems to ambiguous to me. It's not clear that you're merging the descriptor from the super prototype, and only if it's a get/set descriptor. I wonder if this behavior would in any way useful for the value descriptor type?

```js
class Base {
  @nonconfigurable
  kickDog() {}
}

class Derived extends Base {
  @hypotheticalDecoratorThatMerges
  kickDog() {}
  // inherits configurable = false from super class 
}
```

**Comment by silkentrance** [comment]
Nice! How about ``merge`` or just ``inherit``? ``mergeDescriptor`` is awful long :grinning:

**Comment by jayphelps** [comment]
I struggle with super short names that are ambiguous. What happens when we want to add a decorator that also does merging but doesn't merge the descriptor, merges something else.

```js
class Base {
  @merge
  foo = { first: 1 };
}
class Derived extends Base {
  @merge
  foo = { second: 2 };
}

const derived = new Derived();
const { first, second } = derived.foo;
```

That's probably a contrived example since I don't think such a decorator is really useful, but I like to keep this practice consistent even if I can't _yet_ think of a real conflicting use case (that's kinda the point).

That said, I do make exceptions for obviously common conventions like `autobind` which is IMO very confusing if you aren't familiar with that convention, but expected if you are.

I _might_ warm up to `merge` or `inherit`, but I haven't yet. I don't feel that the length of `mergeDescriptor` (or similar) is too long to outweigh the benefit it has of being immensely more self-descriptive to anyone coming into your code later. This is some voodoo confusing shit to begin with so throwing readers a bone is important to me.

**Comment by silkentrance** [comment]
No problem, I use very long and speaking names myself. And one can always alias the name on import.

**Comment by silkentrance** [comment]
@jayphelps 
Since the overall participation is limited to just us two and one third person, I presume that you decide the name for the decorator and off you go :smiley:
