### ISSUE TITLE
apply/Decorators helper

### ISSUE THREAD

**Issue by silkentrance** [jayphelps/core-decorators.js#61]
Please consider pointing out that there is the excellent transformation plugin made by @loganfsmyth that will allow you to use decorators with babel 6.x.

I know that there might be some issues with core decorators, but these need to be fixed anyhow as soon as the new spec arrives.

**Comment by jayphelps** [comment]
@silkentrance is this the same as #36? I've warmed up to that plugin now that it's been so long that babel hasn't reimplemented support so I'm okay with adding a note in the README. Feel free to PR, otherwise I'll try to get to it in a week or so (I'm mobile right now)

**Comment by silkentrance** [comment]
@jayphelps ups, yes, this one was closed. it is the same, but since you began brewing your own cup of tea here, I though it might be a good time to once again...

**Comment by jayphelps** [comment]
Forgot to close this, it's been listed in the README for a while.
