### ISSUE TITLE
chaining multiple @decorate's fails in 0.12.1

### ISSUE THREAD

**Issue by TrejGun** [jayphelps/core-decorators.js#73]
in 0.12.0 this code works

```js
"use strict";

import {decorate} from "core-decorators";

function decorator(fn) {
	return function inner(...args) {
		console.log("fn", fn);
		return fn.bind(this)(...args);
	};
}

const obj = new class {

	@decorate(decorator)
	@decorate(decorator)
	test(...args) {
		console.log(...args);
	}

};

obj.test();
```

in 0.12.1 it throws 

```
test.js:43
                return fn.bind(this).apply(undefined, arguments);
                         ^

TypeError: Cannot read property 'bind' of undefined
    at _class.inner (test.js:8:10)
    at Object.<anonymous> (test.js:22:5)
    at Module._compile (module.js:413:34)

```

**Comment by jayphelps** [comment]
This is a toughy...

The issue is that we [switched to lazily applying the decorator](https://github.com/jayphelps/core-decorators.js/commit/a7a194cf3f387a10b019caa1dff8ee3a04f4024b) using a getter so that we can apply it to the instance instead of the prototype which resolved another bug. The test suite missed it because I wasn't testing chaining multiple `@decorate` calls. I'm experimenting with some solutions.

**Comment by jayphelps** [comment]
@TrejGun I believe I've fixed it with #74, gonna let the code stew for a day. Feel free to try if you can.

You can try it out either by building core-decorators yourself or you can download this zip and extract the contents into your `node_modules/core-decorators/*`
[core-decorators.zip](https://github.com/jayphelps/core-decorators.js/files/229080/core-decorators.zip)

**Comment by TrejGun** [comment]
LGTM, thanks!

**Comment by TrejGun** [comment]
will this work with something like 
```
    @autobind
    @decorate(decorator)
    test(...args) {
        console.log(...args);
    }
```
and
```
    @decorate(decorator)
    @autobind
    test(...args) {
        console.log(...args);
    }
```
?

**Comment by jayphelps** [comment]
@TrejGun not at the moment (one breaks the other invokes the method pre-emptively internally so be careful)

This whole thing has been an awful juggling between different requests (e.g. #65), so I'm considering reverting back to the old way of decorating the prototype instead and then introducing an option or a new decorator that will then opt-into decorating the instance instead.
