### ISSUE TITLE
Circular dependency in lib/private/utils.js

### ISSUE THREAD

**Issue by louy** [jayphelps/core-decorators.js#92]
Hi,

There's a circular dependency in this package and it's breaking my webpack build:

```
ERROR in Circular dependency detected:
node_modules/core-decorators/lib/private/utils.js -> node_modules/core-decorators/lib/lazy-initialize.js -> node_modules/core-decorators/lib/private/utils.js
```

**Comment by jayphelps** [comment]
Circular dependencies are not always a bug. This instance of it is known and intended.Are you using this https://github.com/aackerman/circular-dependency-plugin to detect cycles or something?

I'll definitely take a look at refactoring things, but no promises. Cycles can be fine.

**Comment by jayphelps** [comment]
If that's the plugin you're using, it supposes excluding files from its checks--you probably want to excuse all of node_modules.

**Comment by louy** [comment]
It was. I was able to get rid of the warnings. Apparently another one broke my build and not this one so I'm not sure whether you want to keep this issue open or not. Either way thank you for your help :)

**Comment by jayphelps** [comment]
@louy phew! good to hear. Thanks!
