### ISSUE TITLE
@throttle trailing edge not as expected

### ISSUE THREAD

**Issue by bcowgill** [jayphelps/core-decorators.js#94]
I expected that throttling a call with leading false, trailing true would finally issue the call using the parameters of the final call not the leading call.

i.e. if you are calling @throttle(500, {leading: false, trailing: true}) _check(index) {...}

and rendering 23 consecutive rows rapidly, need to check if the final rendered index is high enough to trigger a fetch of more data.

it actually calls _check(0) instead of _check(23)

**Comment by episodeyang** [comment]
I just ran into the same problem. Same as @bcowgill reported.

**Comment by jayphelps** [comment]
fix published as v0.15.0

**Comment by bcowgill** [comment]
verified as fixing the issue I had. thanks loads.
